#!/usr/bin/env python

def main(args):
    conf = plistlib.readPlist('/Library/Preferences/SystemConfiguration/LinkLayerAddresses.plist')
    interfaces = conf['interfaces']
    for interface in interfaces:
        name = interface['name']
        lladdr = interface['lladdr']
        os.system('/sbin/ifconfig %s lladdr %s' % (name, lladdr))

if __name__ == '__main__':
    main(sys.argv)
